server:
  port: 8082

spring:
  application:
    name: material-service

  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://postgres-db:5432/materialdb}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:aryan}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  servlet:
    multipart:
      enabled: true
      max-file-size: 50MB
      max-request-size: 50MB

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

supabase:
  url: ${SUPABASE_URL:https://your-project.supabase.co}
  service-key: ${SUPABASE_SERVICE_KEY:your-service-role-key}
  bucket: ${SUPABASE_BUCKET:lecture-materials}
