spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      server:
        webflux:
          globalcors:
            cors-configurations:
              '[/**]':
                          allowedOrigins: "http://localhost:5173"
                          allowedMethods:
                            - GET
                            - POST
                            - PUT
                            - DELETE
                            - OPTIONS
                          allowedHeaders: "*"
                          allowCredentials: true
          discovery:
            locator:
              lower-case-service-id: true

server:
  port: 8765
