server:
  port: 8765

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: quiz-service
          uri: lb://quiz-service
          predicates:
            - Path=/quiz/**
          filters:
            - StripPrefix=1
            - AuthFilter

        - id: question-service
          uri: lb://question-service
          predicates:
            - Path=/question/**
          filters:
            - StripPrefix=1
            - AuthFilter

        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/user/**
          filters:
            - StripPrefix=1
            - AuthFilter
