server:
  port: 8082

spring:
  application:
    name: material-service

  datasource:
    driver-class-name: org.postgresql.Driver
#    url: jdbc:postgresql://postgres-db:5432/materialdb
    url: jdbc:postgresql://127.0.0.1:5432/materialdb
    username: postgres
    password: aryan

  jpa:
    hibernate:
      ddl-auto: update
#    show-sql: true

  servlet:
    multipart:
      enabled: true
      max-file-size: 50MB
      max-request-size: 50MB

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

supabase:
  url: ${SUPABASE_URL:https://icjkkfcxmwdvilbrirqe.supabase.co}
  service-key: ${SUPABASE_SERVICE_KEY:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImljamtrZmN4bXdkdmlsYnJpcnFlIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc3MzQ4OTg5MiwiZXhwIjoyMDg5MDY1ODkyfQ.t7vPxooLpe1VcgeX4-pLKZu1XLqvcIqXIx14JVLXJak}
  bucket: ${SUPABASE_BUCKET:lecture-materials}
